image: node:18.14

stages:
  - installation
  - triggers

installation:
  stage: installation
  cache:
    key: $CI_COMMIT_REF_NAME
    policy: push
    paths:
      - node_modules
  script:
    - npm ci

ui_kit:
  stage: triggers
  trigger:
    include: packages/ui-kit/.gitlab-ci.yml
  rules:
    - changes:
        - packages/ui-kit/*
